version: '3.7'

services:
  mysql:
    container_name: mysql_test
    image: meloana/inf21dw1g07:mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root      
    networks:
      - my-network
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    container_name: app
    image: meloana/inf21dw1g07:app1
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - my-network

networks:
  my-network: